<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Packet.Kiss" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Axcall\Axcall.csproj" />
    <ProjectReference Include="..\..\src\Axsocks\Axsocks.csproj" />
    <ProjectReference Include="..\..\src\Axinetd\Axinetd.csproj" />
    <ProjectReference Include="..\..\src\Axtun\Axtun.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Integration\Resources\network.yaml" />
    <EmbeddedResource Include="Integration\Resources\bpq32.cfg" />
    <EmbeddedResource Include="Integration\Peers\Resources\Dockerfile" />
    <EmbeddedResource Include="Integration\Peers\Resources\with-kiss-pty.sh" />
    <EmbeddedResource Include="Integration\Peers\Resources\XROUTER.CFG" />
    <EmbeddedResource Include="Integration\Peers\Resources\IPROUTE.SYS" />
    <EmbeddedResource Include="Integration\Peers\Resources\xrouter-network.yaml" />
  </ItemGroup>

</Project>
